name: Download Dataset and Execute Notebook

on: [push]

jobs:
  setup_and_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas matplotlib seaborn scikit-learn jupyter nbformat

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p data
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        kaggle datasets download blastchar/telco-customer-churn -p data --unzip
        ls -la data

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/paez_ramirez_jean_carlos_KNN.ipynb --output notebooks/paez_ramirez_jean_carlos_KNN.ipynb --allow-errors

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/
        git add notebooks/paez_ramirez_jean_carlos_KNN.ipynb
        git diff --staged --quiet || git commit -m "Update notebook and dataset"
        git push