name: Download Dataset and Execute Notebook

on: [push]

jobs:
  setup_and_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas matplotlib seaborn scikit-learn jupyter

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        # Crear la carpeta data si no existe
        mkdir -p data
        
        # Configurar credenciales de Kaggle
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        
        # Descargar el dataset
        kaggle datasets download blastchar/telco-customer-churn -p data --unzip
        
        # Listar contenido de la carpeta data
        ls -la data

    - name: Execute Jupyter Notebook
      run: |
        # Verificar que el notebook existe
        if [ -f "notebooks/Apellido_Nombre_del_estudiante.ipynb" ]; then
          echo "Notebook encontrado. Ejecutando..."
          jupyter nbconvert --to notebook --execute notebooks/Apellido_Nombre_del_estudiante.ipynb --output notebooks/Apellido_Nombre_del_estudiante.ipynb --allow-errors
        else
          echo "Error: El notebook no existe en la ruta especificada."
          exit 1
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add notebooks/Apellido_Nombre_del_estudiante.ipynb
        git diff --staged --quiet || git commit -m "Update executed notebook"
        git push