name: Download Dataset and Execute Notebook

on: [push]

jobs:
  download_and_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: python scripts/download_data.py

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/Apellido_Nombre.ipynb --output notebooks/Apellido_Nombre.ipynb --allow-errors

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add notebooks/Apellido_Nombre.ipynb
        git diff --staged --quiet || git commit -m "Actualización automática del notebook"
        git push