name: Download Dataset and Execute Notebook

on: [push]

jobs:
  setup_and_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas matplotlib seaborn scikit-learn jupyter

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        # Crear la carpeta data si no existe
        mkdir -p data
        
        # Configurar credenciales de Kaggle
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        
        # Descargar el dataset
        kaggle datasets download blastchar/telco-customer-churn -p data --unzip
        
        # Listar contenido de la carpeta data
        ls -la data

    - name: Create notebook if it does not exist
      run: |
        # Crear la carpeta notebooks si no existe
        mkdir -p notebooks
        
        # Verificar si el notebook existe
        if [ ! -f "notebooks/paez_ramirez_jean_carlos_KNN.ipynb" ]; then
          echo "Creando un notebook vacío..."
          echo '{"cells":[],"metadata":{},"nbformat":4,"nbformat_minor":4}' > notebooks/paez_ramirez_jean_carlos_KNN.ipynb
        else
          echo "Notebook encontrado."
        fi

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/paez_ramirez_jean_carlos_KNN.ipynb --output notebooks/paez_ramirez_jean_carlos_KNN.ipynb --allow-errors

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add notebooks/paez_ramirez_jean_carlos_KNN.ipynb
        git diff --staged --quiet || git commit -m "Update executed notebook"
        git push