name: Download Dataset and Execute Notebook

on: [push]

jobs:
  setup_and_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Cambiado a 3.10 para mejor compatibilidad

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas matplotlib seaborn scikit-learn jupyter nbformat

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p data
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        kaggle datasets download blastchar/telco-customer-churn -p data --unzip
        ls -la data

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/
        git diff --staged --quiet || git commit -m "Update dataset"
        git push